/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AdditionalInfoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CapsuleCreationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/EditProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/registration`; params?: Router.UnknownInputParams; } | { pathname: `/SendCapsulePage`; params?: Router.UnknownInputParams; } | { pathname: `/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/context/MyContext`; params?: Router.UnknownInputParams; } | { pathname: `/tab/CameraScreen`; params?: Router.UnknownInputParams; } | { pathname: `/tab/FriendsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/tab/HomeCapsule`; params?: Router.UnknownInputParams; } | { pathname: `/tab/ProfileScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/AdditionalInfoScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/CapsuleCreationScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/EditProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/registration`; params?: Router.UnknownOutputParams; } | { pathname: `/SendCapsulePage`; params?: Router.UnknownOutputParams; } | { pathname: `/SettingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/context/MyContext`; params?: Router.UnknownOutputParams; } | { pathname: `/tab/CameraScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/tab/FriendsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/tab/HomeCapsule`; params?: Router.UnknownOutputParams; } | { pathname: `/tab/ProfileScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/AdditionalInfoScreen${`?${string}` | `#${string}` | ''}` | `/CapsuleCreationScreen${`?${string}` | `#${string}` | ''}` | `/EditProfileScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/registration${`?${string}` | `#${string}` | ''}` | `/SendCapsulePage${`?${string}` | `#${string}` | ''}` | `/SettingsScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/context/MyContext${`?${string}` | `#${string}` | ''}` | `/tab/CameraScreen${`?${string}` | `#${string}` | ''}` | `/tab/FriendsScreen${`?${string}` | `#${string}` | ''}` | `/tab/HomeCapsule${`?${string}` | `#${string}` | ''}` | `/tab/ProfileScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AdditionalInfoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CapsuleCreationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/EditProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/registration`; params?: Router.UnknownInputParams; } | { pathname: `/SendCapsulePage`; params?: Router.UnknownInputParams; } | { pathname: `/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/context/MyContext`; params?: Router.UnknownInputParams; } | { pathname: `/tab/CameraScreen`; params?: Router.UnknownInputParams; } | { pathname: `/tab/FriendsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/tab/HomeCapsule`; params?: Router.UnknownInputParams; } | { pathname: `/tab/ProfileScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
